Add constituency methodology documentation (#57)
* write data structure part of the documentation

* add constituency example part

* Edit the text and add introduction

* add math part

* edit the text of methodology

* edit titles and example code

* Fix errors in validation pages

* correct exacution error

* Add check to PR action

* Increase epochs

* Don't run all epochs in test mode

* Update calibration routine parameters

* Add pct close to EFRS

* Add minimum on PE.py

---------

Co-authored-by: Nikhil Woodruff <nikhil.woodruff@outlook.com>

diff --git a/.github/workflows/pull_request.yaml b/.github/workflows/pull_request.yaml
--- a/.github/workflows/pull_request.yaml
+++ b/.github/workflows/pull_request.yaml
@@ -30,6 +30,8 @@ jobs:
   test:
     name: Build and test
     runs-on: ubuntu-latest
+    env:
+      HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -47,7 +49,19 @@ jobs:
           HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
       - name: Build datasets
         run: make data
+        env:
+          DATA_LITE: true
       - name: Run tests
         run: pytest
       - name: Test documentation builds
         run: make documentation
+
+      - name: Check documentation build
+        run: |
+          for notebook in $(find docs/_build/jupyter_execute -name "*.ipynb"); do
+            if grep -q '"output_type": "error"' "$notebook"; then
+              echo "Error found in $notebook"
+              cat "$notebook"
+              exit 1
+            fi
+          done
